#ifndef QESHIDUSB_GLOBAL_H
#define QESHIDUSB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QESHIDUSB_LIBRARY)
#define QESHIDUSBSHARED_EXPORT Q_DECL_EXPORT
#elif defined(QESHIDUSB_STATIC_LIBRARY)
#define QESHIDUSBSHARED_EXPORT
#else
#define QESHIDUSBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QESHIDUSB_GLOBAL_H
